### ISSUE TITLE
Add Dark Mode Feature

### ISSUE THREAD

**Issue by niteshkmdev** [Nktech-Official/Sudoku-Web-Game-flask#2]
add a button in Navbar to enable Dark Mode. So that players can play this game at night. Don't add skip using Black(0,0,0). Color 
Make it look like professional Dark-Mode. like Github or any other website take inspiration from where ever you want. Comment and with to assign this issue to you .

**Comment by gulshanjakhon** [comment]
Please assign this issue to me

**Comment by Nktech-Official** [comment]
Whoever's dark mode is interesting will be merged. Make it fast' to get prefrence

**Comment by Nktech-Official** [comment]
> Hi @Nktech-Official please check my PR Dark-light mode added #5

Your Dark Mode seriously need's to be redesigned

**Comment by dollygupta07** [comment]
Hi @Nktech-Official, I want to contribute to this issue. Can you assign this to me?
Thanks,

**Comment by Nktech-Official** [comment]
Yeah, Make it Fast, But don't let the design suffer because of it . If Your Design is good Your Pr will definitely be merged so make it clean and don't forget to comment your code 

> Hi @Nktech-Official, I want to contribute to this issue. Can you assign this to me? Thanks,
