### ISSUE TITLE
Cangrats if you win alert

### ISSUE THREAD

**Issue by omarbarrerasosa** [Nktech-Official/Sudoku-Web-Game-flask#9]
I played the game and it works just fine.
Once I finished, I noticed that after checking solution (which one has to do it manually), it doesn't show any alert saying anything.
Should you place an alert saying "Well done!" for example. 
Just a comment.

**Comment by ChancellorCeti** [comment]
Hey I would like to take a stab at this, could you assign it to me?

**Comment by hientranea** [comment]
Hi @Nktech-Official I created the PR https://github.com/Nktech-Official/Sudoku-Web-Game-flask/pull/1 for this issue. Please take a look. Thanks

**Comment by Nktech-Official** [comment]
@hientranea  I have requested Changes from your Side please look into that.

**Comment by hientranea** [comment]
I updated my PR here https://github.com/Nktech-Official/Sudoku-Web-Game-flask/pull/15. Please review it again @Nktech-Official . Thanks.
